### ISSUE TITLE
Project 3: Optimize Orcasound streaming software

### ISSUE THREAD

**Issue by valentina-s** [orcasound/orcagsoc#4]
## Optimize Orcasound streaming software

Improve Orcasound’s audio-streaming performance and intelligence by improving the Python code in the [s3_flac branch of the orcanode repository](https://github.com/orcasound/orcanode/tree/s3_flac).

The new Dockerized orcanode code will include these high-priority feature requests: utilize the reduced-latency Jack audio driver in Linux, rather than ALSA; intelligent recovery of live stream upon power loss or bandwidth limitations; and local loopback.

**Required skills:** Linux, Python, Docker, ffmpeg

**Bonus skills:** Boto, S3FS, other cloud storage CLIs; Linux audio drivers; cron jobs; redis.

**Possible mentors:**  Scott, Val, Steve, Jesse

**References, open-source building blocks and getting started instructions:**

 [s3_flac branch of the orcanode repository](https://github.com/orcasound/orcanode/tree/s3_flac)

**Comment by mcshicks** [comment]
I have created a small PDF with some more detail on this project as well as updating the orcanode projectss board here https://github.com/orcasound/orcanode/projects/1.  
[gsocnotes.pdf](https://github.com/orcasound/orcagsoc/files/4377026/gsocnotes.pdf)

**Comment by dylanwishner** [comment]
Hey everyone, here's my proposal for this project. I'd love to get some feedback on how I can improve it if anyone has the time! https://docs.google.com/document/d/1Kri8I8jo1t2wrIjIRp6ZZt-ps8kkN-9G0H7wZyG-DKc/edit

**Comment by valentina-s** [comment]
I believe this is old now and we don't need it given the new issue. Feel free to reopen if I am wrong. @mcshicks
