### ISSUE TITLE
Project 6: Add and test icons in human detection UI within Orcasound web app

### ISSUE THREAD

**Issue by valentina-s** [orcasound/orcagsoc#7]
## Add and test icons in human detection UI within Orcasound web app

Instead of the free text, enable user to select simple icons when they detect associated sounds (e.g. whale, ship, mystery) within the Orcasound app v2 UI and log icon labels within the Orcasound back end.

**Required skills:** Elixir, [Javascript](url)

**Bonus skills:** experience with user-centered design; Google analytics

**Possible mentors:** Scott (with technical assistance from Orcasound community members Paul, Skander, Mike, and/or Anurag)

**References and open-source building blocks:**
[Beta.orcasound.net](beta.orcasound.net) (access UI for live feed pages via dropdown menu, and note the “I hear something interesting" button)

**Comment by vuthuytrang93** [comment]
I'm interested in working on this issue. Below the link to my Draft Proposal . I am looking forward to your feedback . Thank you  😄 
https://docs.google.com/document/d/19rPbZVxwoB5zgMsvczfCzlWbtcuwxicaLAraGwU5TFM/edit?usp=sharing

**Comment by rudragodse** [comment]
I am interested in solving this issue.

**Comment by rudragodse** [comment]
The link that is shared does not open. Please help

**Comment by vuthuytrang93** [comment]
It happened to me too. The link isn't working on Windown or Linux. Try to open it on a Mac.

**Comment by rudragodse** [comment]
I can improve on the U.I front of listen functionality on the orcasound web app

**Comment by rudragodse** [comment]
I dont have a mac  @vuthuytrang93

**Comment by rudragodse** [comment]
can you suggest some other alternative @vuthuytrang93

**Comment by vuthuytrang93** [comment]
It's a beta version so I dont think it fully works. That's the only way I found. If you are on Slack , ping me there or dm me

**Comment by rudragodse** [comment]
yeah I am on slack. I will ping you

**Comment by rudragodse** [comment]
Are you trangvu on slack @vuthuytrang93

**Comment by apshada** [comment]
@rudragodse @vuthuytrang93  http://beta.orcasound.net/ this link is working check it out for reference

**Comment by scottveirs** [comment]
Sorry had URL markdown reversed. Fixed the link to beta-testing version of web-app.

**Comment by vinayaksh42** [comment]
Hey @scottveirs  , I came across this issue via the 2021 project idea list of Orcasound. I am interested in this project. I have forked both the orcamap and orcamap-react map. What should be the next step to get aligned with the goal of this project?

**Comment by valentina-s** [comment]
I believe this is old, so I will close. Please, reopen if needed.
